//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 05:20:28 PM CEST 
//


package it.polimi.modaclouds.recedingHorizonScaling4Cloud.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for container complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="container">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationTier" type="{}applicationTier" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capacity" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="nCore" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="processingRate" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="maxReserved" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reservedCost" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="onDemandCost" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "container", propOrder = {
    "applicationTier"
})
public class Container {

    @XmlElement(required = true)
    protected List<ApplicationTier> applicationTier;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "capacity", required = true)
    protected double capacity;
    @XmlAttribute(name = "nCore", required = true)
    protected int nCore;
    @XmlAttribute(name = "processingRate", required = true)
    protected double processingRate;
    @XmlAttribute(name = "maxReserved", required = true)
    protected int maxReserved;
    @XmlAttribute(name = "reservedCost", required = true)
    protected double reservedCost;
    @XmlAttribute(name = "onDemandCost", required = true)
    protected double onDemandCost;

    /**
     * Gets the value of the applicationTier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationTier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationTier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationTier }
     * 
     * 
     */
    public List<ApplicationTier> getApplicationTier() {
        if (applicationTier == null) {
            applicationTier = new ArrayList<ApplicationTier>();
        }
        return this.applicationTier;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     */
    public double getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     */
    public void setCapacity(double value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the nCore property.
     * 
     */
    public int getNCore() {
        return nCore;
    }

    /**
     * Sets the value of the nCore property.
     * 
     */
    public void setNCore(int value) {
        this.nCore = value;
    }

    /**
     * Gets the value of the processingRate property.
     * 
     */
    public double getProcessingRate() {
        return processingRate;
    }

    /**
     * Sets the value of the processingRate property.
     * 
     */
    public void setProcessingRate(double value) {
        this.processingRate = value;
    }

    /**
     * Gets the value of the maxReserved property.
     * 
     */
    public int getMaxReserved() {
        return maxReserved;
    }

    /**
     * Sets the value of the maxReserved property.
     * 
     */
    public void setMaxReserved(int value) {
        this.maxReserved = value;
    }

    /**
     * Gets the value of the reservedCost property.
     * 
     */
    public double getReservedCost() {
        return reservedCost;
    }

    /**
     * Sets the value of the reservedCost property.
     * 
     */
    public void setReservedCost(double value) {
        this.reservedCost = value;
    }

    /**
     * Gets the value of the onDemandCost property.
     * 
     */
    public double getOnDemandCost() {
        return onDemandCost;
    }

    /**
     * Sets the value of the onDemandCost property.
     * 
     */
    public void setOnDemandCost(double value) {
        this.onDemandCost = value;
    }

}
