#!/bin/sh

export AR_HOME="${AR_HOME:-$PWD}"

if [ ! -e "$AR_HOME" ]
then
    echo "$AR_HOME does not exist" 1>&2
    exit 1
fi

JAR="$AR_HOME/modaclouds-autoscalingReasoner.jar"
CLASS="it.polimi.modaclouds.recedingHorizonScaling4Cloud.Main"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    AR_HOME=`cygpath -w "$AR_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

#exec java  $JVM_ARGS -jar "$JAR" "$@"
exec java $JVM_ARGS -cp "$JAR:lib/*" $CLASS "$@"